ALTER TABLE public.autosave_schedules
  ADD COLUMN IF NOT EXISTS initial_limit_per_instance INTEGER NOT NULL DEFAULT 20,
  ADD COLUMN IF NOT EXISTS daily_increment INTEGER NOT NULL DEFAULT 5,
  ADD COLUMN IF NOT EXISTS max_limit_per_instance INTEGER NOT NULL DEFAULT 100,
  ADD COLUMN IF NOT EXISTS days_executed INTEGER NOT NULL DEFAULT 0;