ALTER TABLE public.verify_results ADD COLUMN IF NOT EXISTS var6 TEXT DEFAULT NULL;
ALTER TABLE public.verify_results ADD COLUMN IF NOT EXISTS var7 TEXT DEFAULT NULL;
ALTER TABLE public.verify_results ADD COLUMN IF NOT EXISTS var8 TEXT DEFAULT NULL;
ALTER TABLE public.verify_results ADD COLUMN IF NOT EXISTS var9 TEXT DEFAULT NULL;
ALTER TABLE public.verify_results ADD COLUMN IF NOT EXISTS var10 TEXT DEFAULT NULL;