ALTER TABLE public.service_contacts
  ADD COLUMN IF NOT EXISTS interest TEXT,
  ADD COLUMN IF NOT EXISTS estimated_value NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS priority TEXT DEFAULT 'media',
  ADD COLUMN IF NOT EXISTS responsible TEXT,
  ADD COLUMN IF NOT EXISTS segment TEXT,
  ADD COLUMN IF NOT EXISTS cpf_cnpj TEXT,
  ADD COLUMN IF NOT EXISTS channel TEXT DEFAULT 'WhatsApp',
  ADD COLUMN IF NOT EXISTS description TEXT;