ALTER TABLE public.autosave_schedules
  ADD COLUMN IF NOT EXISTS pause_every_min INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS pause_every_max INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS pause_duration_min INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS pause_duration_max INTEGER NOT NULL DEFAULT 0;